image: google/cloud-sdk:latest

definitions:
  steps:
    # - step: &lint-backend
    #     name: Lint Backend
    #     image: golangci/golangci-lint:v1.55
    #     script:
    #       - cd server
    #       - golangci-lint run --timeout=5m

    # - step: &lint-frontend
    #     name: Lint Frontend
    #     image: node:20
    #     caches:
    #       - node
    #     script:
    #       - cd client
    #       - npm ci
    #       - npm run lint

    # - step: &test-backend
    #     name: Test Backend
    #     image: golang:1.21
    #     script:
    #       - cd server
    #       - go mod download
    #       - go test -v ./...

    - step: &build-backend
        name: Build Backend
        services:
          - docker
        script:
          - cd server
          - export DOCKER_BUILDKIT=0
          - docker build -t backend:${BITBUCKET_COMMIT} .
          - cd ..
          - docker save backend:${BITBUCKET_COMMIT} -o backend.tar
        artifacts:
          - backend.tar

    - step: &build-frontend
        name: Build Frontend
        services:
          - docker
        script:
          - cd client
          - export DOCKER_BUILDKIT=0
          - docker build --build-arg VITE_API_URL=${BACKEND_URL} -t frontend:${BITBUCKET_COMMIT} .
          - cd ..
          - docker save frontend:${BITBUCKET_COMMIT} -o frontend.tar
        artifacts:
          - frontend.tar

    - step: &push-images
        name: Push to Artifact Registry
        services:
          - docker
        script:
          # Authenticate with Google Cloud
          - echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > /tmp/key.json
          - gcloud auth activate-service-account --key-file=/tmp/key.json
          - gcloud auth configure-docker ${_REGION}-docker.pkg.dev
          
          # Load and tag images
          - docker load -i backend.tar
          - docker load -i frontend.tar
          - docker tag backend:${BITBUCKET_COMMIT} ${_REGION}-docker.pkg.dev/${PROJECT_ID}/listify/backend:${BITBUCKET_COMMIT}
          - docker tag frontend:${BITBUCKET_COMMIT} ${_REGION}-docker.pkg.dev/${PROJECT_ID}/listify/frontend:${BITBUCKET_COMMIT}
          
          # Push images
          - docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/listify/backend:${BITBUCKET_COMMIT}
          - docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/listify/frontend:${BITBUCKET_COMMIT}

    - step: &deploy
        name: Deploy to Cloud Run
        script:
          # Authenticate with Google Cloud
          - echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > /tmp/key.json
          - gcloud auth activate-service-account --key-file=/tmp/key.json
          
          # Deploy backend
          - gcloud run deploy listify-backend --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/listify/backend:${BITBUCKET_COMMIT} --region=${_REGION} --platform=managed --allow-unauthenticated --set-env-vars=MONGODB_URI=${MONGODB_URI}
          
          # Deploy frontend
          - gcloud run deploy listify-frontend --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/listify/frontend:${BITBUCKET_COMMIT} --region=${_REGION} --platform=managed --allow-unauthenticated

  services:
    docker:
      memory: 2048
  
  caches:
    node: ~/.npm

pipelines:
  branches:
    main:
      # - step: *lint-backend
      # - step: *lint-frontend
      # - step: *test-backend
      - step: *build-backend
      - step: *build-frontend
      - step: *push-images
      - step: *deploy

  # turned off because of bitbicket ci/cd free time limit
  # pull-requests:
  #   '**':
  #     - step: *test-backend
  #     - step: *lint-backend
  #     - step: *lint-frontend

clone:
  depth: 1

options:
  docker: true
  max-time: 30 